# Development override for hot reloading and better developer experience
# Usage: docker-compose -f docker-compose.yml -f docker-compose.clerk.yml -f docker-compose.dev.yml up

services:
  # Clerk backend with hot reload
  clerk:
    volumes:
      # Mount source code for hot reloading
      - ./Clerk:/app:cached
      # Exclude venv to avoid conflicts
      - /app/venv
      # Mount logs directory
      - ./Clerk/logs:/app/logs
    environment:
      # Development settings
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      # Ensure proper CORS for development
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:8010,http://localhost:5173
    # Use reload flag for development
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]
    # Disable health check in dev for easier debugging
    healthcheck:
      disable: true

  # Frontend development server instead of static build
  clerk-frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      # Mount entire frontend directory
      - ./Clerk/frontend:/app:cached
      # Use named volume for node_modules to avoid platform conflicts
      - clerk_frontend_node_modules:/app/node_modules
    environment:
      # Development environment
      - NODE_ENV=development
      # Vite specific settings
      - VITE_API_URL=http://localhost:8010
      - VITE_WS_URL=http://localhost:8010
      - VITE_AUTH_ENABLED=false
      # Ensure Supabase URLs are set
      - VITE_SUPABASE_URL=${SUPABASE_URL:-http://localhost:8000}
      - VITE_SUPABASE_ANON_KEY=${ANON_KEY}
    ports:
      - "3000:3000"  # Vite default port
    command: >
      sh -c "
        if [ ! -d node_modules ]; then
          echo 'Installing dependencies...'
          npm ci
        fi
        echo 'Starting Vite dev server...'
        npm run dev -- --host 0.0.0.0 --port 3000
      "
    depends_on:
      - clerk
    networks:
      - localai-network

  # Override Caddy to proxy to Vite dev server
  caddy:
    environment:
      # In dev, proxy to Vite instead of static files
      - FRONTEND_URL=http://clerk-frontend:3000
    volumes:
      # Mount custom Caddyfile for development if needed
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
    depends_on:
      - clerk-frontend
      - clerk

  # Qdrant with persistent storage
  qdrant:
    volumes:
      # Persist vector storage data
      - ./qdrant_storage:/qdrant/storage:cached

  # Development database tools (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    networks:
      - localai-network
    profiles:
      - debug

  # Redis Commander for Redis inspection (optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - localai-network
    profiles:
      - debug

# Named volumes for better performance
volumes:
  clerk_frontend_node_modules:
    name: localai_clerk_frontend_node_modules

# Additional development configurations
networks:
  localai-network:
    name: localai_default
    external: true