services:
  flowise:
    ports:
      - 127.0.0.1:3001:3001

  open-webui:
    ports:
      - 127.0.0.1:8080:8080

  n8n:
    ports:
      - 127.0.0.1:5678:5678

  qdrant:
    ports:
      - 127.0.0.1:6333:6333
      - 127.0.0.1:6334:6334

  neo4j:
    ports:
      - 127.0.0.1:7473:7473
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7687:7687

  langfuse-worker:
    ports:
      - 127.0.0.1:3030:3030

  langfuse-web:
    ports:
      - 127.0.0.1:3000:3000

  clickhouse:
    ports:
      - 127.0.0.1:8123:8123
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9009:9009

  minio:
    ports:
      - 127.0.0.1:9011:9000
      - 127.0.0.1:9012:9001

  # Note: postgres port exposure is handled by docker-compose.postgres-expose.yml
  # to avoid conflicts when using start_services_with_postgres.py                

  redis:
    ports:
      - 127.0.0.1:6379:6379

  searxng:
    ports:
      - 127.0.0.1:8081:8080

  legal-motion-api:
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - ALLOWED_HOSTS=["localhost", "legal-motion-api", "host.docker.internal"]
      - ALLOWED_ORIGINS=["http://localhost:8009", "http://localhost:5678", "http://localhost:3000"]
    # For hot reload during development
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      # Mount source code for hot reload
      - ./legal-motion-api:/app
      # Preserve logs
      - ./legal-motion-api/logs:/app/logs
    # Expose port for direct access during development
    ports:
      - "8888:8000"  # Direct access at localhost:8888 (bypassing Caddy)