version: '3.8'

services:
  clerk:
    environment:
      # Box API Configuration
      - BOX_CLIENT_ID=${BOX_CLIENT_ID}
      - BOX_CLIENT_SECRET=${BOX_CLIENT_SECRET}
      - BOX_ENTERPRISE_ID=${BOX_ENTERPRISE_ID}
      - BOX_JWT_KEY_ID=${BOX_JWT_KEY_ID}
      - BOX_PRIVATE_KEY=${BOX_PRIVATE_KEY}
      - BOX_PASSPHRASE=${BOX_PASSPHRASE}
      - COHERE_API_KEY=${COHERE_API_KEY}
      # LLM Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=https://api.openai.com/v1
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CONTEXT_LLM_MODEL=${CONTEXT_LLM_MODEL:-gpt-4o-mini}
      # Qdrant Configuration (internal Docker network)
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_GRPC_PORT=6334
      - QDRANT_HTTPS=false
      # Motion Drafting Configuration
      - MOTION_PRIMARY_MODEL=${MOTION_PRIMARY_MODEL}
      - MOTION_REVIEW_MODEL=${MOTION_REVIEW_MODEL}
      - MOTION_CACHE_SIZE_MB=${MOTION_CACHE_SIZE_MB}
      # Other settings
      - ENABLE_COST_TRACKING=${ENABLE_COST_TRACKING:-true}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # CORS for frontend
      - CORS_ORIGINS=http://localhost:8010,http://localhost:3000